### ISSUE TITLE
contacts组件发现如下问题

### ISSUE THREAD

**Issue by JasonAndMaron** [vkingw/react-contacts#1]
1、搜索部门时可以勾选部门,并且勾选的部门会出现在下面的选择框中
2、选择部门勾选全部，再次选择其他部门再次勾选全部，之前勾选的被清空

**Comment by JasonAndMaron** [comment]
因不能传图片，具体情况我已经发你邮箱了

**Comment by vkingw** [comment]
新版本已经修复或者已经通过修改使用方法来解决此问题。
